In [1]:
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from string import punctuation

In [2]:
df1=pd.read_csv('complaints.csv')

In [3]:
df1

Date received                                            Product  \
0          2019-09-24                                    Debt collection   
1          2019-09-19  Credit reporting, credit repair services, or o...   
2          2019-10-25  Credit reporting, credit repair services, or o...   
3          2019-11-08                                    Debt collection   
4          2019-02-08                              Vehicle loan or lease   
...               ...                                                ...   
1571892    2016-07-11                                      Consumer Loan   
1571893    2017-01-24                                    Debt collection   
1571894    2015-03-26                                           Mortgage   
1571895    2015-12-12                                           Mortgage   
1571896    2016-08-09                                        Credit card   

                                    Sub-product  \
0                                 I do not know   
1                              Credit reporting   
2                              Credit reporting   
3                                 I do not know   
4                                         Lease   
...                                         ...   
1571892                            Vehicle loan   
1571893                           I do not know   
1571894                            FHA mortgage   
1571895  Conventional adjustable mortgage (ARM)   
1571896                                     NaN   

                                                     Issue  \
0                        Attempts to collect debt not owed   
1                     Incorrect information on your report   
2                     Incorrect information on your report   
3                                    Communication tactics   
4        Problem with a credit reporting company's inve...   
...                                                    ...   
1571892                         Managing the loan or lease   
1571893                              Communication tactics   
1571894           Loan servicing, payments, escrow account   
1571895           Loan servicing, payments, escrow account   
1571896                                  Transaction issue   

                                                 Sub-issue  \
0                                        Debt is not yours   
1                      Information belongs to someone else   
2                      Information belongs to someone else   
3                               Frequent or repeated calls   
4        Their investigation did not fix an error on yo...   
...                                                    ...   
1571892                                                NaN   
1571893                    Threatened to take legal action   
1571894                                                NaN   
1571895                                                NaN   
1571896                                                NaN   

                              Consumer complaint narrative  \
0        transworld systems inc. \nis trying to collect...   
1                                                      NaN   
2        I would like to request the suppression of the...   
3        Over the past 2 weeks, I have been receiving e...   
4                                                      NaN   
...                                                    ...   
1571892  I was on automatic payment for my car loan. In...   
1571893  I recieved a collections call from an unknown ...   
1571894  On XXXX XXXX, 2015, I contacted XXXX XXXX, who...   
1571895  I can not get from chase who services my mortg...   
1571896  I made a payment to CITI XXXX Credit Card on X...   

                                   Company public response  \
0                                                      NaN   
1        Company has responded to the consumer and the ...   
2        Company has responded to the consumer and the ...   

In [4]:
df1.nunique()

Date received                      3067
Product                              18
Sub-product                          76
Issue                               166
Sub-issue                           218
Consumer complaint narrative     488113
Company public response              10
Company                            5611
State                                63
ZIP code                          23922
Tags                                  3
Consumer consent provided?            4
Submitted via                         6
Date sent to company               3016
Company response to consumer          8
Timely response?                      2
Consumer disputed?                    2
Complaint ID                    1571897
dtype: int64

In [5]:
df1.isnull().sum()

Date received                         0
Product                               0
Sub-product                      235165
Issue                                 0
Sub-issue                        565938
Consumer complaint narrative    1051910
Company public response          975517
Company                               0
State                             26664
ZIP code                         149195
Tags                            1357114
Consumer consent provided?       633683
Submitted via                         0
Date sent to company                  0
Company response to consumer          1
Timely response?                      0
Consumer disputed?               803420
Complaint ID                          0
dtype: int64

In [6]:
df1['Product'].value_counts()

Credit reporting, credit repair services, or other personal consumer reports    379932
Mortgage                                                                        300236
Debt collection                                                                 290174
Credit reporting                                                                140432
Credit card                                                                      89190
Bank account or service                                                          86206
Credit card or prepaid card                                                      74012
Checking or savings account                                                      61847
Student loan                                                                     57609
Consumer Loan                                                                    31604
Vehicle loan or lease                                                            16742
Money transfer, virtual currency, or money 

In [7]:
df=df1[['Product','Consumer complaint narrative']]

In [8]:
df['Consumer complaint narrative'].isnull().sum()

1051910

In [9]:
df=df[df['Consumer complaint narrative'].notnull()]

In [10]:
df['Product'].value_counts()

Credit reporting, credit repair services, or other personal consumer reports    159043
Debt collection                                                                 111688
Mortgage                                                                         63829
Credit card or prepaid card                                                      35093
Credit reporting                                                                 31588
Student loan                                                                     25786
Checking or savings account                                                      20652
Credit card                                                                      18838
Bank account or service                                                          14885
Consumer Loan                                                                     9473
Vehicle loan or lease                                                             8788
Money transfer, virtual currency, or money 

In [11]:
df['Product'].nunique()

18

In [12]:
df['Product']=df['Product'].replace({'Credit reporting':'Credit reporting, credit repair services, or other personal consumer reports',
                      'Credit card':'Credit card or prepaid card',
                      'Payday loan':'Payday loan, title loan, or personal loan',
                      'Prepaid card':'Credit card or prepaid card',
                      'Student loan':'loans',
                      'Consumer Loan':'loans',
                      'Vehicle loan or lease':'loans',
                      'Payday loan, title loan, or personal loan':'loans',
                    'Payday loan':'loans'})

In [13]:
df['Product']=df['Product'].replace({'Money transfers':'Money transfer, virtual currency, or money service'})

In [14]:
df['Product'].value_counts()

Credit reporting, credit repair services, or other personal consumer reports    190631
Debt collection                                                                 111688
Mortgage                                                                         63829
Credit card or prepaid card                                                      55381
loans                                                                            52710
Checking or savings account                                                      20652
Bank account or service                                                          14885
Money transfer, virtual currency, or money service                                9903
Other financial service                                                            292
Virtual currency                                                                    16
Name: Product, dtype: int64

In [15]:
df['Product'].value_counts()

Credit reporting, credit repair services, or other personal consumer reports    190631
Debt collection                                                                 111688
Mortgage                                                                         63829
Credit card or prepaid card                                                      55381
loans                                                                            52710
Checking or savings account                                                      20652
Bank account or service                                                          14885
Money transfer, virtual currency, or money service                                9903
Other financial service                                                            292
Virtual currency                                                                    16
Name: Product, dtype: int64

In [16]:
df['Product']=df['Product'].replace({'Other financial service':'Money transfer, virtual currency, or money service',
                                    'Virtual currency':'Money transfer, virtual currency, or money service'})

In [17]:
df.nunique()

Product                              8
Consumer complaint narrative    488113
dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le=LabelEncoder


In [20]:
df['category']=le.fit_transform(df,df['Product'])

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:252: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.classes_, y = _encode(y, encode=True)


In [21]:
y=df[['Product','category']]

In [22]:
df.drop('Product',axis=1,inplace=True)

In [23]:
df

Consumer complaint narrative  category
0        transworld systems inc. \nis trying to collect...         4
2        I would like to request the suppression of the...         3
3        Over the past 2 weeks, I have been receiving e...         4
11       I was sold access to an event digitally, of wh...         5
12       While checking my credit report I noticed thre...         4
...                                                    ...       ...
1571892  I was on automatic payment for my car loan. In...         7
1571893  I recieved a collections call from an unknown ...         4
1571894  On XXXX XXXX, 2015, I contacted XXXX XXXX, who...         6
1571895  I can not get from chase who services my mortg...         6
1571896  I made a payment to CITI XXXX Credit Card on X...         2

[519987 rows x 2 columns]

In [24]:
df.index=np.arange(0,len(df))

In [25]:
df

Consumer complaint narrative  category
0       transworld systems inc. \nis trying to collect...         4
1       I would like to request the suppression of the...         3
2       Over the past 2 weeks, I have been receiving e...         4
3       I was sold access to an event digitally, of wh...         5
4       While checking my credit report I noticed thre...         4
...                                                   ...       ...
519982  I was on automatic payment for my car loan. In...         7
519983  I recieved a collections call from an unknown ...         4
519984  On XXXX XXXX, 2015, I contacted XXXX XXXX, who...         6
519985  I can not get from chase who services my mortg...         6
519986  I made a payment to CITI XXXX Credit Card on X...         2

[519987 rows x 2 columns]

In [26]:
df['category'].value_counts()

3    190631
4    111688
6     63829
2     55381
7     52710
1     20652
0     14885
5     10211
Name: category, dtype: int64

In [27]:
a=df[df['category']==0].sample(n=10000,random_state=0)
b=df[df['category']==1].sample(n=10000,random_state=0)
c=df[df['category']==2].sample(n=10000,random_state=0)
d=df[df['category']==3].sample(n=10000,random_state=0)
e=df[df['category']==4].sample(n=10000,random_state=0)
f=df[df['category']==5].sample(n=10000,random_state=0)
g=df[df['category']==6].sample(n=10000,random_state=0)
h=df[df['category']==7].sample(n=10000,random_state=0)

In [28]:
dfsample=pd.concat([a,b,c,d,e,f,g,h],sort=False)

In [29]:
dfsample['category'].value_counts().sum()

80000

In [30]:
dfsample.index=np.arange(0,80000)

In [31]:
from nltk.tokenize import word_tokenize
from nltk.stem.lancaster import LancasterStemmer

In [32]:
unw=set(stopwords.words('english')+list(punctuation))

In [33]:
stemmer = LancasterStemmer()

In [34]:
corpus=dfsample['Consumer complaint narrative']

In [35]:
corpus

0        I wrote a check for {$700.00} for rent to my l...
1        PayPal is holding onto funds for a transaction...
2        Citizen Bank has been taking out monthly fees ...
3        On XXXX/XXXX/2015 I issued an XXXX eCheck to W...
4        A Wells Fargo account was opened in my name ( ...
                               ...                        
79995    I am going through a lay off due to workforce ...
79996    On XX/XX/XXXX XXXX sent me a notice that they ...
79997    I called in on  XXXX   XXXX   2017 spoke w ith...
79998    This is a line of credit from synchrony bank, ...
79999    there is a company called cashnet who keeps ca...
Name: Consumer complaint narrative, Length: 80000, dtype: object

In [36]:
final_corpus= []
for i in range(len(corpus)):
    text = word_tokenize(corpus[i].lower())
    text = [stemmer.stem(x) for x in text if x not in unw]
    final = " ".join(text)
    final_corpus.append(final)

In [2]:
b='aa aa aa'
b.split()

['aa', 'aa', 'aa']

In [3]:
" ".join(b.split())

'aa aa aa'

In [37]:
final_corpus

["wrot check 700.00 rent landlord xxxx xxxx begin xxxx landlord mobl deposit check cam account per us howev day lat someon stol check cash money deduc back landlord 's account check stol money stol report claim immedy found bank wel fargo report bank xxxx xxxx xxxx howev bank refus reimburs 700.00 stol ask bank wo n't refund us ref us bank theref issu pass back for bank refund money stol refus 700.00 unacceiv",
 'payp hold onto fund transact fulfil 2 week ago xxxx xxxx sold laptop ebay ship us xxxx next day 24 hour delivery wednesday buy laptop tim payp releas fund instead claim receiv valid track numb pat fals attempt help fix re-sending track detail xxxx3 tim pack sent via xxxx xxxx xxxx numb xxxx provid payp dat ship receiv fund 7 day attempt esc cas direct payp sent track detail claim valid sev tim tri esc cas ev receiv autom mess tel track detail invalid irrelev erron fact claim account new account payp ebay const us posit feedback decad believ hold onto fund cas 600.00 long perio

In [38]:
new=pd.DataFrame(final_corpus)

In [39]:
new['target']=dfsample['category']

In [4]:
new

NameError: name 'new' is not defined

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [42]:
vector= tfidf.fit_transform(new[0])

In [43]:
X = vector.toarray()
y = new['target']

In [44]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [45]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

In [46]:
mnb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
y_pred=mnb.predict(X_test)

In [48]:
y_pred_train=mnb.predict(X_train)

In [49]:
y_pred

array([1, 0, 6, ..., 3, 0, 7])

In [50]:
from sklearn.metrics import classification_report,confusion_matrix

In [51]:
confusion_matrix(y_train,y_pred_train)

array([[4527, 1386,  397,  116,   59,  295,  196,   98],
       [ 907, 5409,  229,   79,   25,  284,   61,   51],
       [ 322,  461, 5505,  267,  156,  166,   53,  163],
       [  46,   57,  446, 5479,  433,   34,  181,  367],
       [  77,   96,  293,  621, 5097,   42,  191,  448],
       [ 273,  802,  211,   16,   35, 5406,   83,  132],
       [  80,   49,   56,   75,   34,   27, 6570,   94],
       [ 111,  132,  242,  245,  280,   52,  171, 5704]])

In [52]:
print(confusion_matrix(y_test,y_pred))

[[1565  818  211   58   24  123   82   45]
 [ 528 2092  102   23   13  141   37   19]
 [ 117  224 2189  119   77   80   25   76]
 [  24   29  184 2232  198   18   94  178]
 [  40   45  140  305 2266   17   93  229]
 [ 128  382   93   11   20 2310   53   45]
 [  59   28   33   35   15    8 2792   45]
 [  59   51  125  130  139   26  107 2426]]


In [53]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.62      0.53      0.57      2926
           1       0.57      0.71      0.63      2955
           2       0.71      0.75      0.73      2907
           3       0.77      0.75      0.76      2957
           4       0.82      0.72      0.77      3135
           5       0.85      0.76      0.80      3042
           6       0.85      0.93      0.89      3015
           7       0.79      0.79      0.79      3063

    accuracy                           0.74     24000
   macro avg       0.75      0.74      0.74     24000
weighted avg       0.75      0.74      0.74     24000



In [54]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.71      0.64      0.67      7074
           1       0.64      0.77      0.70      7045
           2       0.75      0.78      0.76      7093
           3       0.79      0.78      0.79      7043
           4       0.83      0.74      0.79      6865
           5       0.86      0.78      0.82      6958
           6       0.88      0.94      0.91      6985
           7       0.81      0.82      0.82      6937

    accuracy                           0.78     56000
   macro avg       0.78      0.78      0.78     56000
weighted avg       0.78      0.78      0.78     56000



In [55]:
from sklearn.metrics import f1_score